### ISSUE TITLE
fileSizeLimitBytes option not available

### ISSUE THREAD

**Issue by Vignesh-coder-coder** [serilog-contrib/Serilog.Sinks.AmazonS3#16]
Can't create rolling file using file size. it creates new file for every request.

**Comment by SeppPenner** [comment]
That's because I don't use the https://github.com/serilog/serilog-sinks-file sink anymore, I now use the https://github.com/serilog/serilog-sinks-periodicbatching now. The reason for this was that the file sink isn't extensible (E.g. the main classes are `internal`).

The reasons:
* I didn't just want to copy-paste the file sink.
* I didn't want to maintain all changes in the file sink manually
* There were performance issues as described in https://github.com/SeppPenner/Serilog.Sinks.AmazonS3/issues/4

You can specify the options, e.g. `BatchSizeLimit` or so as described under https://github.com/SeppPenner/Serilog.Sinks.AmazonS3/blob/master/HowToUse.md#configuration-options.

**Comment by SeppPenner** [comment]
Ah, now I understand the problem. Sorry for that, I guess I forgot to update the how to use section.

**Comment by SeppPenner** [comment]
This is now fixed with https://github.com/SeppPenner/Serilog.Sinks.AmazonS3/commit/b7467ab97a2185c17f510766e0267270aef57616.

**Comment by Vignesh-coder-coder** [comment]
Thanks
