### ISSUE TITLE
Unable to influence size of files in the bucket

### ISSUE THREAD

**Issue by alexgurman** [serilog-contrib/Serilog.Sinks.AmazonS3#23]
I have tried to play with batchSizeLimit value on Serilog.LoggerConfigurationAmazonS3Extensions.AmazonS3 but the size of files produced by logging remains pretty small - usually about 2K, though occasionally up to 11K. How do I make it bigger? Using 10000 currently.

**Comment by SeppPenner** [comment]
I will have to check this.

**Comment by alexgurman** [comment]
thank you

**Comment by SeppPenner** [comment]
If I understand it correctly from https://github.com/serilog/serilog-sinks-periodicbatching/blob/dev/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs and https://github.com/serilog/serilog-sinks-periodicbatching:

There are the parameters

* BatchSizeLimit: The number of events that should be sent per batch (So, if you have 10000, there should be 10000 events per file in AWS)
* Period: The check period (How often the timer checks whether there is a batch `push` neccessary or not
* EagerlyEmitFirstEvent: If the first event should directly be emitted even if the batch is not filled up yet
* QueueLimit: The limit of the background queue that stores all the events for the batch (Should be bigger than the `BatchSizeLimit` parameter).

The first version(s) of the sink hat a different mechanism while using the https://github.com/serilog/serilog-sinks-file sink, but there serious issues occurred with the lifecycle hooks (See https://github.com/serilog/serilog-sinks-file#extensibility), meaning e.g. that the files were not written or access errors to the files occurred, and so on. That's why the sink now uses the batching sink and therefore you can sadly only influence the file size via the number of events.

I hope, this makes it clear and helps you, if not, or if there is a bug, just leave me a message here again, please :)

**Comment by SeppPenner** [comment]
Here is the official description I found in the batching sink's parameters:

```csharp
/// <summary>
  /// Initialization options for <see cref="T:Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink" />.
  /// </summary>
  public class PeriodicBatchingSinkOptions
  {
    /// <summary>
    /// Eagerly emit a batch containing the first received event, regardless of
    /// the target batch size or batching time. This helps with perceived "liveness"
    /// when running/debugging applications interactively. The default is <c>true</c>.
    /// </summary>
    public bool EagerlyEmitFirstEvent { get; set; } = true;

    /// <summary>
    /// The maximum number of events to include in a single batch. The default is <c>1000</c>.
    /// </summary>
    public int BatchSizeLimit { get; set; } = 1000;

    /// <summary>
    /// The time to wait between checking for event batches. The default is two seconds.
    /// </summary>
    public TimeSpan Period { get; set; } = TimeSpan.FromSeconds(2.0);

    /// <summary>
    /// Maximum number of events to hold in the sink's internal queue, or <c>null</c>
    /// for an unbounded queue. The default is <c>10000</c>.
    /// </summary>
    public int? QueueLimit { get; set; } = new int?(100000);
  }
```
